// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.21.12
// source: parking.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'

export const protobufPackage = ''

export interface Parking {
    wifiScanning?: WifiScanning | undefined
    scanResults?: ScanResults | undefined
    wifiStatus?: DeviceStatus | undefined
    parkingStatus?: ParkingStatus | undefined
    parkingEvent?: ParkingEvent | undefined
    wifiConfig?: WifiConfig | undefined
}

export interface WifiScanning {}

export interface ScanResults {
    /** max_count: 10 (nanopb) */
    accessPoints: ScanResults_AP[]
}

export enum ScanResults_WifiAuthMode {
    WIFI_AUTH_OPEN = 0,
    WIFI_AUTH_WEP = 1,
    WIFI_AUTH_WPA_PSK = 2,
    WIFI_AUTH_WPA2_PSK = 3,
    WIFI_AUTH_WPA_WPA2_PSK = 4,
    WIFI_AUTH_ENTERPRISE = 5,
    /** WIFI_AUTH_WPA3_PSK - WIFI_AUTH_WPA2_ENTERPRISE         = 5; */
    WIFI_AUTH_WPA3_PSK = 6,
    WIFI_AUTH_WPA2_WPA3_PSK = 7,
    WIFI_AUTH_WAPI_PSK = 8,
    WIFI_AUTH_OWE = 9,
    WIFI_AUTH_WPA3_ENT_192 = 10,
    WIFI_AUTH_WPA3_EXT_PSK = 11,
    WIFI_AUTH_WPA3_EXT_PSK_MIXED_MODE = 12,
    WIFI_AUTH_DPP = 13,
    WIFI_AUTH_WPA3_ENTERPRISE = 14,
    WIFI_AUTH_WPA2_WPA3_ENTERPRISE = 15,
    WIFI_AUTH_WPA_ENTERPRISE = 16,
    UNRECOGNIZED = -1,
}

export function scanResults_WifiAuthModeFromJSON(object: any): ScanResults_WifiAuthMode {
    switch (object) {
        case 0:
        case 'WIFI_AUTH_OPEN':
            return ScanResults_WifiAuthMode.WIFI_AUTH_OPEN
        case 1:
        case 'WIFI_AUTH_WEP':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WEP
        case 2:
        case 'WIFI_AUTH_WPA_PSK':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WPA_PSK
        case 3:
        case 'WIFI_AUTH_WPA2_PSK':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WPA2_PSK
        case 4:
        case 'WIFI_AUTH_WPA_WPA2_PSK':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WPA_WPA2_PSK
        case 5:
        case 'WIFI_AUTH_ENTERPRISE':
            return ScanResults_WifiAuthMode.WIFI_AUTH_ENTERPRISE
        case 6:
        case 'WIFI_AUTH_WPA3_PSK':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WPA3_PSK
        case 7:
        case 'WIFI_AUTH_WPA2_WPA3_PSK':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WPA2_WPA3_PSK
        case 8:
        case 'WIFI_AUTH_WAPI_PSK':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WAPI_PSK
        case 9:
        case 'WIFI_AUTH_OWE':
            return ScanResults_WifiAuthMode.WIFI_AUTH_OWE
        case 10:
        case 'WIFI_AUTH_WPA3_ENT_192':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WPA3_ENT_192
        case 11:
        case 'WIFI_AUTH_WPA3_EXT_PSK':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WPA3_EXT_PSK
        case 12:
        case 'WIFI_AUTH_WPA3_EXT_PSK_MIXED_MODE':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WPA3_EXT_PSK_MIXED_MODE
        case 13:
        case 'WIFI_AUTH_DPP':
            return ScanResults_WifiAuthMode.WIFI_AUTH_DPP
        case 14:
        case 'WIFI_AUTH_WPA3_ENTERPRISE':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WPA3_ENTERPRISE
        case 15:
        case 'WIFI_AUTH_WPA2_WPA3_ENTERPRISE':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WPA2_WPA3_ENTERPRISE
        case 16:
        case 'WIFI_AUTH_WPA_ENTERPRISE':
            return ScanResults_WifiAuthMode.WIFI_AUTH_WPA_ENTERPRISE
        case -1:
        case 'UNRECOGNIZED':
        default:
            return ScanResults_WifiAuthMode.UNRECOGNIZED
    }
}

export function scanResults_WifiAuthModeToJSON(object: ScanResults_WifiAuthMode): string {
    switch (object) {
        case ScanResults_WifiAuthMode.WIFI_AUTH_OPEN:
            return 'WIFI_AUTH_OPEN'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WEP:
            return 'WIFI_AUTH_WEP'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WPA_PSK:
            return 'WIFI_AUTH_WPA_PSK'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WPA2_PSK:
            return 'WIFI_AUTH_WPA2_PSK'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WPA_WPA2_PSK:
            return 'WIFI_AUTH_WPA_WPA2_PSK'
        case ScanResults_WifiAuthMode.WIFI_AUTH_ENTERPRISE:
            return 'WIFI_AUTH_ENTERPRISE'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WPA3_PSK:
            return 'WIFI_AUTH_WPA3_PSK'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WPA2_WPA3_PSK:
            return 'WIFI_AUTH_WPA2_WPA3_PSK'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WAPI_PSK:
            return 'WIFI_AUTH_WAPI_PSK'
        case ScanResults_WifiAuthMode.WIFI_AUTH_OWE:
            return 'WIFI_AUTH_OWE'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WPA3_ENT_192:
            return 'WIFI_AUTH_WPA3_ENT_192'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WPA3_EXT_PSK:
            return 'WIFI_AUTH_WPA3_EXT_PSK'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WPA3_EXT_PSK_MIXED_MODE:
            return 'WIFI_AUTH_WPA3_EXT_PSK_MIXED_MODE'
        case ScanResults_WifiAuthMode.WIFI_AUTH_DPP:
            return 'WIFI_AUTH_DPP'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WPA3_ENTERPRISE:
            return 'WIFI_AUTH_WPA3_ENTERPRISE'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WPA2_WPA3_ENTERPRISE:
            return 'WIFI_AUTH_WPA2_WPA3_ENTERPRISE'
        case ScanResults_WifiAuthMode.WIFI_AUTH_WPA_ENTERPRISE:
            return 'WIFI_AUTH_WPA_ENTERPRISE'
        case ScanResults_WifiAuthMode.UNRECOGNIZED:
        default:
            return 'UNRECOGNIZED'
    }
}

export interface ScanResults_AP {
    /** max_size: 32 (nanopb) */
    ssid: string
    /** 6 bytes MAC address (nanopb) */
    bssid: Uint8Array
    rssi: number
    channel: number
    encryption: ScanResults_WifiAuthMode
}

export interface DeviceStatus {
    connected: boolean
    wifiMode: DeviceStatus_WifiMode
    /** max_size: 32 (nanopb) */
    staSsid: string
    /** max_size: 16 (nanopb) */
    staIp: string
    /** max_size: 32 (nanopb) */
    apSsid: string
    /** max_size: 16 (nanopb) */
    apIp: string
    /** max_size: 64 (nanopb) */
    apPassword: string
    rssi: number
    channel: number
    freeHeap: number
    minFreeHeap: number
    maxFreeBlockSize: number
    uptimeSeconds: number
}

export enum DeviceStatus_WifiMode {
    WIFI_MODE_NULL = 0,
    WIFI_MODE_STA = 1,
    WIFI_MODE_AP = 2,
    WIFI_MODE_APSTA = 3,
    WIFI_MODE_NAN = 4,
    UNRECOGNIZED = -1,
}

export function deviceStatus_WifiModeFromJSON(object: any): DeviceStatus_WifiMode {
    switch (object) {
        case 0:
        case 'WIFI_MODE_NULL':
            return DeviceStatus_WifiMode.WIFI_MODE_NULL
        case 1:
        case 'WIFI_MODE_STA':
            return DeviceStatus_WifiMode.WIFI_MODE_STA
        case 2:
        case 'WIFI_MODE_AP':
            return DeviceStatus_WifiMode.WIFI_MODE_AP
        case 3:
        case 'WIFI_MODE_APSTA':
            return DeviceStatus_WifiMode.WIFI_MODE_APSTA
        case 4:
        case 'WIFI_MODE_NAN':
            return DeviceStatus_WifiMode.WIFI_MODE_NAN
        case -1:
        case 'UNRECOGNIZED':
        default:
            return DeviceStatus_WifiMode.UNRECOGNIZED
    }
}

export function deviceStatus_WifiModeToJSON(object: DeviceStatus_WifiMode): string {
    switch (object) {
        case DeviceStatus_WifiMode.WIFI_MODE_NULL:
            return 'WIFI_MODE_NULL'
        case DeviceStatus_WifiMode.WIFI_MODE_STA:
            return 'WIFI_MODE_STA'
        case DeviceStatus_WifiMode.WIFI_MODE_AP:
            return 'WIFI_MODE_AP'
        case DeviceStatus_WifiMode.WIFI_MODE_APSTA:
            return 'WIFI_MODE_APSTA'
        case DeviceStatus_WifiMode.WIFI_MODE_NAN:
            return 'WIFI_MODE_NAN'
        case DeviceStatus_WifiMode.UNRECOGNIZED:
        default:
            return 'UNRECOGNIZED'
    }
}

export interface WifiConfig {
    /** max_size: 32 (nanopb) */
    staSsid: string
    /** max_size: 64 (nanopb) */
    staPassword: string
    /** max_size: 32 (nanopb) */
    apSsid: string
    /** max_size: 64 (nanopb) */
    apPassword: string
}

export interface ParkingStatus {
    /** max_count: 15 (nanopb) */
    slots: SlotStatus[]
}

export interface SlotStatus {
    status: SlotStatus_Status
    /** raw RFID tag bytes (10 bytes each), max_count: 15 (nanopb) */
    rfid: Uint8Array[]
    palletId: number
}

export enum SlotStatus_Status {
    UNKNOWN = 0,
    NO_PALLET = 1,
    EMPTY = 2,
    OCCUPIED = 3,
    PROCESSING = 4,
    PENDING = 5,
    UNRECOGNIZED = -1,
}

export function slotStatus_StatusFromJSON(object: any): SlotStatus_Status {
    switch (object) {
        case 0:
        case 'UNKNOWN':
            return SlotStatus_Status.UNKNOWN
        case 1:
        case 'NO_PALLET':
            return SlotStatus_Status.NO_PALLET
        case 2:
        case 'EMPTY':
            return SlotStatus_Status.EMPTY
        case 3:
        case 'OCCUPIED':
            return SlotStatus_Status.OCCUPIED
        case 4:
        case 'PROCESSING':
            return SlotStatus_Status.PROCESSING
        case 5:
        case 'PENDING':
            return SlotStatus_Status.PENDING
        case -1:
        case 'UNRECOGNIZED':
        default:
            return SlotStatus_Status.UNRECOGNIZED
    }
}

export function slotStatus_StatusToJSON(object: SlotStatus_Status): string {
    switch (object) {
        case SlotStatus_Status.UNKNOWN:
            return 'UNKNOWN'
        case SlotStatus_Status.NO_PALLET:
            return 'NO_PALLET'
        case SlotStatus_Status.EMPTY:
            return 'EMPTY'
        case SlotStatus_Status.OCCUPIED:
            return 'OCCUPIED'
        case SlotStatus_Status.PROCESSING:
            return 'PROCESSING'
        case SlotStatus_Status.PENDING:
            return 'PENDING'
        case SlotStatus_Status.UNRECOGNIZED:
        default:
            return 'UNRECOGNIZED'
    }
}

export interface ParkingEvent {
    eventId: number
    slotId: number
    /** Unix epoch time in milliseconds */
    timestamp: number
    eventType: ParkingEvent_EventType
    rfid: Uint8Array
    isDone: boolean
}

export enum ParkingEvent_EventType {
    UNKNOWN = 0,
    IN = 1,
    OUT = 2,
    UNRECOGNIZED = -1,
}

export function parkingEvent_EventTypeFromJSON(object: any): ParkingEvent_EventType {
    switch (object) {
        case 0:
        case 'UNKNOWN':
            return ParkingEvent_EventType.UNKNOWN
        case 1:
        case 'IN':
            return ParkingEvent_EventType.IN
        case 2:
        case 'OUT':
            return ParkingEvent_EventType.OUT
        case -1:
        case 'UNRECOGNIZED':
        default:
            return ParkingEvent_EventType.UNRECOGNIZED
    }
}

export function parkingEvent_EventTypeToJSON(object: ParkingEvent_EventType): string {
    switch (object) {
        case ParkingEvent_EventType.UNKNOWN:
            return 'UNKNOWN'
        case ParkingEvent_EventType.IN:
            return 'IN'
        case ParkingEvent_EventType.OUT:
            return 'OUT'
        case ParkingEvent_EventType.UNRECOGNIZED:
        default:
            return 'UNRECOGNIZED'
    }
}

function createBaseParking(): Parking {
    return {
        wifiScanning: undefined,
        scanResults: undefined,
        wifiStatus: undefined,
        parkingStatus: undefined,
        parkingEvent: undefined,
        wifiConfig: undefined,
    }
}

export const Parking: MessageFns<Parking> = {
    encode(message: Parking, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
        if (message.wifiScanning !== undefined) {
            WifiScanning.encode(message.wifiScanning, writer.uint32(10).fork()).join()
        }
        if (message.scanResults !== undefined) {
            ScanResults.encode(message.scanResults, writer.uint32(18).fork()).join()
        }
        if (message.wifiStatus !== undefined) {
            DeviceStatus.encode(message.wifiStatus, writer.uint32(26).fork()).join()
        }
        if (message.parkingStatus !== undefined) {
            ParkingStatus.encode(message.parkingStatus, writer.uint32(34).fork()).join()
        }
        if (message.parkingEvent !== undefined) {
            ParkingEvent.encode(message.parkingEvent, writer.uint32(42).fork()).join()
        }
        if (message.wifiConfig !== undefined) {
            WifiConfig.encode(message.wifiConfig, writer.uint32(50).fork()).join()
        }
        return writer
    },

    decode(input: BinaryReader | Uint8Array, length?: number): Parking {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
        const end = length === undefined ? reader.len : reader.pos + length
        const message = createBaseParking()
        while (reader.pos < end) {
            const tag = reader.uint32()
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break
                    }

                    message.wifiScanning = WifiScanning.decode(reader, reader.uint32())
                    continue
                }
                case 2: {
                    if (tag !== 18) {
                        break
                    }

                    message.scanResults = ScanResults.decode(reader, reader.uint32())
                    continue
                }
                case 3: {
                    if (tag !== 26) {
                        break
                    }

                    message.wifiStatus = DeviceStatus.decode(reader, reader.uint32())
                    continue
                }
                case 4: {
                    if (tag !== 34) {
                        break
                    }

                    message.parkingStatus = ParkingStatus.decode(reader, reader.uint32())
                    continue
                }
                case 5: {
                    if (tag !== 42) {
                        break
                    }

                    message.parkingEvent = ParkingEvent.decode(reader, reader.uint32())
                    continue
                }
                case 6: {
                    if (tag !== 50) {
                        break
                    }

                    message.wifiConfig = WifiConfig.decode(reader, reader.uint32())
                    continue
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break
            }
            reader.skip(tag & 7)
        }
        return message
    },

    fromJSON(object: any): Parking {
        return {
            wifiScanning: isSet(object.wifiScanning)
                ? WifiScanning.fromJSON(object.wifiScanning)
                : isSet(object.wifi_scanning)
                  ? WifiScanning.fromJSON(object.wifi_scanning)
                  : undefined,
            scanResults: isSet(object.scanResults)
                ? ScanResults.fromJSON(object.scanResults)
                : isSet(object.scan_results)
                  ? ScanResults.fromJSON(object.scan_results)
                  : undefined,
            wifiStatus: isSet(object.wifiStatus)
                ? DeviceStatus.fromJSON(object.wifiStatus)
                : isSet(object.wifi_status)
                  ? DeviceStatus.fromJSON(object.wifi_status)
                  : undefined,
            parkingStatus: isSet(object.parkingStatus)
                ? ParkingStatus.fromJSON(object.parkingStatus)
                : isSet(object.parking_status)
                  ? ParkingStatus.fromJSON(object.parking_status)
                  : undefined,
            parkingEvent: isSet(object.parkingEvent)
                ? ParkingEvent.fromJSON(object.parkingEvent)
                : isSet(object.parking_event)
                  ? ParkingEvent.fromJSON(object.parking_event)
                  : undefined,
            wifiConfig: isSet(object.wifiConfig)
                ? WifiConfig.fromJSON(object.wifiConfig)
                : isSet(object.wifi_config)
                  ? WifiConfig.fromJSON(object.wifi_config)
                  : undefined,
        }
    },

    toJSON(message: Parking): unknown {
        const obj: any = {}
        if (message.wifiScanning !== undefined) {
            obj.wifiScanning = WifiScanning.toJSON(message.wifiScanning)
        }
        if (message.scanResults !== undefined) {
            obj.scanResults = ScanResults.toJSON(message.scanResults)
        }
        if (message.wifiStatus !== undefined) {
            obj.wifiStatus = DeviceStatus.toJSON(message.wifiStatus)
        }
        if (message.parkingStatus !== undefined) {
            obj.parkingStatus = ParkingStatus.toJSON(message.parkingStatus)
        }
        if (message.parkingEvent !== undefined) {
            obj.parkingEvent = ParkingEvent.toJSON(message.parkingEvent)
        }
        if (message.wifiConfig !== undefined) {
            obj.wifiConfig = WifiConfig.toJSON(message.wifiConfig)
        }
        return obj
    },

    create<I extends Exact<DeepPartial<Parking>, I>>(base?: I): Parking {
        return Parking.fromPartial(base ?? ({} as any))
    },
    fromPartial<I extends Exact<DeepPartial<Parking>, I>>(object: I): Parking {
        const message = createBaseParking()
        message.wifiScanning =
            object.wifiScanning !== undefined && object.wifiScanning !== null
                ? WifiScanning.fromPartial(object.wifiScanning)
                : undefined
        message.scanResults =
            object.scanResults !== undefined && object.scanResults !== null
                ? ScanResults.fromPartial(object.scanResults)
                : undefined
        message.wifiStatus =
            object.wifiStatus !== undefined && object.wifiStatus !== null
                ? DeviceStatus.fromPartial(object.wifiStatus)
                : undefined
        message.parkingStatus =
            object.parkingStatus !== undefined && object.parkingStatus !== null
                ? ParkingStatus.fromPartial(object.parkingStatus)
                : undefined
        message.parkingEvent =
            object.parkingEvent !== undefined && object.parkingEvent !== null
                ? ParkingEvent.fromPartial(object.parkingEvent)
                : undefined
        message.wifiConfig =
            object.wifiConfig !== undefined && object.wifiConfig !== null
                ? WifiConfig.fromPartial(object.wifiConfig)
                : undefined
        return message
    },
}

function createBaseWifiScanning(): WifiScanning {
    return {}
}

export const WifiScanning: MessageFns<WifiScanning> = {
    encode(_: WifiScanning, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
        return writer
    },

    decode(input: BinaryReader | Uint8Array, length?: number): WifiScanning {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
        const end = length === undefined ? reader.len : reader.pos + length
        const message = createBaseWifiScanning()
        while (reader.pos < end) {
            const tag = reader.uint32()
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break
            }
            reader.skip(tag & 7)
        }
        return message
    },

    fromJSON(_: any): WifiScanning {
        return {}
    },

    toJSON(_: WifiScanning): unknown {
        const obj: any = {}
        return obj
    },

    create<I extends Exact<DeepPartial<WifiScanning>, I>>(base?: I): WifiScanning {
        return WifiScanning.fromPartial(base ?? ({} as any))
    },
    fromPartial<I extends Exact<DeepPartial<WifiScanning>, I>>(_: I): WifiScanning {
        const message = createBaseWifiScanning()
        return message
    },
}

function createBaseScanResults(): ScanResults {
    return { accessPoints: [] }
}

export const ScanResults: MessageFns<ScanResults> = {
    encode(
        message: ScanResults,
        writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
        for (const v of message.accessPoints) {
            ScanResults_AP.encode(v!, writer.uint32(10).fork()).join()
        }
        return writer
    },

    decode(input: BinaryReader | Uint8Array, length?: number): ScanResults {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
        const end = length === undefined ? reader.len : reader.pos + length
        const message = createBaseScanResults()
        while (reader.pos < end) {
            const tag = reader.uint32()
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break
                    }

                    message.accessPoints.push(
                        ScanResults_AP.decode(reader, reader.uint32()),
                    )
                    continue
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break
            }
            reader.skip(tag & 7)
        }
        return message
    },

    fromJSON(object: any): ScanResults {
        return {
            accessPoints: globalThis.Array.isArray(object?.accessPoints)
                ? object.accessPoints.map((e: any) => ScanResults_AP.fromJSON(e))
                : globalThis.Array.isArray(object?.access_points)
                  ? object.access_points.map((e: any) => ScanResults_AP.fromJSON(e))
                  : [],
        }
    },

    toJSON(message: ScanResults): unknown {
        const obj: any = {}
        if (message.accessPoints?.length) {
            obj.accessPoints = message.accessPoints.map((e) => ScanResults_AP.toJSON(e))
        }
        return obj
    },

    create<I extends Exact<DeepPartial<ScanResults>, I>>(base?: I): ScanResults {
        return ScanResults.fromPartial(base ?? ({} as any))
    },
    fromPartial<I extends Exact<DeepPartial<ScanResults>, I>>(object: I): ScanResults {
        const message = createBaseScanResults()
        message.accessPoints =
            object.accessPoints?.map((e) => ScanResults_AP.fromPartial(e)) || []
        return message
    },
}

function createBaseScanResults_AP(): ScanResults_AP {
    return { ssid: '', bssid: new Uint8Array(0), rssi: 0, channel: 0, encryption: 0 }
}

export const ScanResults_AP: MessageFns<ScanResults_AP> = {
    encode(
        message: ScanResults_AP,
        writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
        if (message.ssid !== '') {
            writer.uint32(10).string(message.ssid)
        }
        if (message.bssid.length !== 0) {
            writer.uint32(18).bytes(message.bssid)
        }
        if (message.rssi !== 0) {
            writer.uint32(24).int32(message.rssi)
        }
        if (message.channel !== 0) {
            writer.uint32(32).uint32(message.channel)
        }
        if (message.encryption !== 0) {
            writer.uint32(40).int32(message.encryption)
        }
        return writer
    },

    decode(input: BinaryReader | Uint8Array, length?: number): ScanResults_AP {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
        const end = length === undefined ? reader.len : reader.pos + length
        const message = createBaseScanResults_AP()
        while (reader.pos < end) {
            const tag = reader.uint32()
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break
                    }

                    message.ssid = reader.string()
                    continue
                }
                case 2: {
                    if (tag !== 18) {
                        break
                    }

                    message.bssid = reader.bytes()
                    continue
                }
                case 3: {
                    if (tag !== 24) {
                        break
                    }

                    message.rssi = reader.int32()
                    continue
                }
                case 4: {
                    if (tag !== 32) {
                        break
                    }

                    message.channel = reader.uint32()
                    continue
                }
                case 5: {
                    if (tag !== 40) {
                        break
                    }

                    message.encryption = reader.int32() as any
                    continue
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break
            }
            reader.skip(tag & 7)
        }
        return message
    },

    fromJSON(object: any): ScanResults_AP {
        return {
            ssid: isSet(object.ssid) ? globalThis.String(object.ssid) : '',
            bssid: isSet(object.bssid)
                ? bytesFromBase64(object.bssid)
                : new Uint8Array(0),
            rssi: isSet(object.rssi) ? globalThis.Number(object.rssi) : 0,
            channel: isSet(object.channel) ? globalThis.Number(object.channel) : 0,
            encryption: isSet(object.encryption)
                ? scanResults_WifiAuthModeFromJSON(object.encryption)
                : 0,
        }
    },

    toJSON(message: ScanResults_AP): unknown {
        const obj: any = {}
        if (message.ssid !== '') {
            obj.ssid = message.ssid
        }
        if (message.bssid.length !== 0) {
            obj.bssid = base64FromBytes(message.bssid)
        }
        if (message.rssi !== 0) {
            obj.rssi = Math.round(message.rssi)
        }
        if (message.channel !== 0) {
            obj.channel = Math.round(message.channel)
        }
        if (message.encryption !== 0) {
            obj.encryption = scanResults_WifiAuthModeToJSON(message.encryption)
        }
        return obj
    },

    create<I extends Exact<DeepPartial<ScanResults_AP>, I>>(base?: I): ScanResults_AP {
        return ScanResults_AP.fromPartial(base ?? ({} as any))
    },
    fromPartial<I extends Exact<DeepPartial<ScanResults_AP>, I>>(
        object: I,
    ): ScanResults_AP {
        const message = createBaseScanResults_AP()
        message.ssid = object.ssid ?? ''
        message.bssid = object.bssid ?? new Uint8Array(0)
        message.rssi = object.rssi ?? 0
        message.channel = object.channel ?? 0
        message.encryption = object.encryption ?? 0
        return message
    },
}

function createBaseDeviceStatus(): DeviceStatus {
    return {
        connected: false,
        wifiMode: 0,
        staSsid: '',
        staIp: '',
        apSsid: '',
        apIp: '',
        apPassword: '',
        rssi: 0,
        channel: 0,
        freeHeap: 0,
        minFreeHeap: 0,
        maxFreeBlockSize: 0,
        uptimeSeconds: 0,
    }
}

export const DeviceStatus: MessageFns<DeviceStatus> = {
    encode(
        message: DeviceStatus,
        writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
        if (message.connected !== false) {
            writer.uint32(8).bool(message.connected)
        }
        if (message.wifiMode !== 0) {
            writer.uint32(16).int32(message.wifiMode)
        }
        if (message.staSsid !== '') {
            writer.uint32(26).string(message.staSsid)
        }
        if (message.staIp !== '') {
            writer.uint32(34).string(message.staIp)
        }
        if (message.apSsid !== '') {
            writer.uint32(42).string(message.apSsid)
        }
        if (message.apIp !== '') {
            writer.uint32(50).string(message.apIp)
        }
        if (message.apPassword !== '') {
            writer.uint32(58).string(message.apPassword)
        }
        if (message.rssi !== 0) {
            writer.uint32(64).int32(message.rssi)
        }
        if (message.channel !== 0) {
            writer.uint32(72).uint32(message.channel)
        }
        if (message.freeHeap !== 0) {
            writer.uint32(80).uint32(message.freeHeap)
        }
        if (message.minFreeHeap !== 0) {
            writer.uint32(88).uint32(message.minFreeHeap)
        }
        if (message.maxFreeBlockSize !== 0) {
            writer.uint32(96).uint32(message.maxFreeBlockSize)
        }
        if (message.uptimeSeconds !== 0) {
            writer.uint32(104).uint32(message.uptimeSeconds)
        }
        return writer
    },

    decode(input: BinaryReader | Uint8Array, length?: number): DeviceStatus {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
        const end = length === undefined ? reader.len : reader.pos + length
        const message = createBaseDeviceStatus()
        while (reader.pos < end) {
            const tag = reader.uint32()
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break
                    }

                    message.connected = reader.bool()
                    continue
                }
                case 2: {
                    if (tag !== 16) {
                        break
                    }

                    message.wifiMode = reader.int32() as any
                    continue
                }
                case 3: {
                    if (tag !== 26) {
                        break
                    }

                    message.staSsid = reader.string()
                    continue
                }
                case 4: {
                    if (tag !== 34) {
                        break
                    }

                    message.staIp = reader.string()
                    continue
                }
                case 5: {
                    if (tag !== 42) {
                        break
                    }

                    message.apSsid = reader.string()
                    continue
                }
                case 6: {
                    if (tag !== 50) {
                        break
                    }

                    message.apIp = reader.string()
                    continue
                }
                case 7: {
                    if (tag !== 58) {
                        break
                    }

                    message.apPassword = reader.string()
                    continue
                }
                case 8: {
                    if (tag !== 64) {
                        break
                    }

                    message.rssi = reader.int32()
                    continue
                }
                case 9: {
                    if (tag !== 72) {
                        break
                    }

                    message.channel = reader.uint32()
                    continue
                }
                case 10: {
                    if (tag !== 80) {
                        break
                    }

                    message.freeHeap = reader.uint32()
                    continue
                }
                case 11: {
                    if (tag !== 88) {
                        break
                    }

                    message.minFreeHeap = reader.uint32()
                    continue
                }
                case 12: {
                    if (tag !== 96) {
                        break
                    }

                    message.maxFreeBlockSize = reader.uint32()
                    continue
                }
                case 13: {
                    if (tag !== 104) {
                        break
                    }

                    message.uptimeSeconds = reader.uint32()
                    continue
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break
            }
            reader.skip(tag & 7)
        }
        return message
    },

    fromJSON(object: any): DeviceStatus {
        return {
            connected: isSet(object.connected)
                ? globalThis.Boolean(object.connected)
                : false,
            wifiMode: isSet(object.wifiMode)
                ? deviceStatus_WifiModeFromJSON(object.wifiMode)
                : isSet(object.wifi_mode)
                  ? deviceStatus_WifiModeFromJSON(object.wifi_mode)
                  : 0,
            staSsid: isSet(object.staSsid)
                ? globalThis.String(object.staSsid)
                : isSet(object.sta_ssid)
                  ? globalThis.String(object.sta_ssid)
                  : '',
            staIp: isSet(object.staIp)
                ? globalThis.String(object.staIp)
                : isSet(object.sta_ip)
                  ? globalThis.String(object.sta_ip)
                  : '',
            apSsid: isSet(object.apSsid)
                ? globalThis.String(object.apSsid)
                : isSet(object.ap_ssid)
                  ? globalThis.String(object.ap_ssid)
                  : '',
            apIp: isSet(object.apIp)
                ? globalThis.String(object.apIp)
                : isSet(object.ap_ip)
                  ? globalThis.String(object.ap_ip)
                  : '',
            apPassword: isSet(object.apPassword)
                ? globalThis.String(object.apPassword)
                : isSet(object.ap_password)
                  ? globalThis.String(object.ap_password)
                  : '',
            rssi: isSet(object.rssi) ? globalThis.Number(object.rssi) : 0,
            channel: isSet(object.channel) ? globalThis.Number(object.channel) : 0,
            freeHeap: isSet(object.freeHeap)
                ? globalThis.Number(object.freeHeap)
                : isSet(object.free_heap)
                  ? globalThis.Number(object.free_heap)
                  : 0,
            minFreeHeap: isSet(object.minFreeHeap)
                ? globalThis.Number(object.minFreeHeap)
                : isSet(object.min_free_heap)
                  ? globalThis.Number(object.min_free_heap)
                  : 0,
            maxFreeBlockSize: isSet(object.maxFreeBlockSize)
                ? globalThis.Number(object.maxFreeBlockSize)
                : isSet(object.max_free_block_size)
                  ? globalThis.Number(object.max_free_block_size)
                  : 0,
            uptimeSeconds: isSet(object.uptimeSeconds)
                ? globalThis.Number(object.uptimeSeconds)
                : isSet(object.uptime_seconds)
                  ? globalThis.Number(object.uptime_seconds)
                  : 0,
        }
    },

    toJSON(message: DeviceStatus): unknown {
        const obj: any = {}
        if (message.connected !== false) {
            obj.connected = message.connected
        }
        if (message.wifiMode !== 0) {
            obj.wifiMode = deviceStatus_WifiModeToJSON(message.wifiMode)
        }
        if (message.staSsid !== '') {
            obj.staSsid = message.staSsid
        }
        if (message.staIp !== '') {
            obj.staIp = message.staIp
        }
        if (message.apSsid !== '') {
            obj.apSsid = message.apSsid
        }
        if (message.apIp !== '') {
            obj.apIp = message.apIp
        }
        if (message.apPassword !== '') {
            obj.apPassword = message.apPassword
        }
        if (message.rssi !== 0) {
            obj.rssi = Math.round(message.rssi)
        }
        if (message.channel !== 0) {
            obj.channel = Math.round(message.channel)
        }
        if (message.freeHeap !== 0) {
            obj.freeHeap = Math.round(message.freeHeap)
        }
        if (message.minFreeHeap !== 0) {
            obj.minFreeHeap = Math.round(message.minFreeHeap)
        }
        if (message.maxFreeBlockSize !== 0) {
            obj.maxFreeBlockSize = Math.round(message.maxFreeBlockSize)
        }
        if (message.uptimeSeconds !== 0) {
            obj.uptimeSeconds = Math.round(message.uptimeSeconds)
        }
        return obj
    },

    create<I extends Exact<DeepPartial<DeviceStatus>, I>>(base?: I): DeviceStatus {
        return DeviceStatus.fromPartial(base ?? ({} as any))
    },
    fromPartial<I extends Exact<DeepPartial<DeviceStatus>, I>>(object: I): DeviceStatus {
        const message = createBaseDeviceStatus()
        message.connected = object.connected ?? false
        message.wifiMode = object.wifiMode ?? 0
        message.staSsid = object.staSsid ?? ''
        message.staIp = object.staIp ?? ''
        message.apSsid = object.apSsid ?? ''
        message.apIp = object.apIp ?? ''
        message.apPassword = object.apPassword ?? ''
        message.rssi = object.rssi ?? 0
        message.channel = object.channel ?? 0
        message.freeHeap = object.freeHeap ?? 0
        message.minFreeHeap = object.minFreeHeap ?? 0
        message.maxFreeBlockSize = object.maxFreeBlockSize ?? 0
        message.uptimeSeconds = object.uptimeSeconds ?? 0
        return message
    },
}

function createBaseWifiConfig(): WifiConfig {
    return { staSsid: '', staPassword: '', apSsid: '', apPassword: '' }
}

export const WifiConfig: MessageFns<WifiConfig> = {
    encode(message: WifiConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
        if (message.staSsid !== '') {
            writer.uint32(10).string(message.staSsid)
        }
        if (message.staPassword !== '') {
            writer.uint32(18).string(message.staPassword)
        }
        if (message.apSsid !== '') {
            writer.uint32(26).string(message.apSsid)
        }
        if (message.apPassword !== '') {
            writer.uint32(34).string(message.apPassword)
        }
        return writer
    },

    decode(input: BinaryReader | Uint8Array, length?: number): WifiConfig {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
        const end = length === undefined ? reader.len : reader.pos + length
        const message = createBaseWifiConfig()
        while (reader.pos < end) {
            const tag = reader.uint32()
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break
                    }

                    message.staSsid = reader.string()
                    continue
                }
                case 2: {
                    if (tag !== 18) {
                        break
                    }

                    message.staPassword = reader.string()
                    continue
                }
                case 3: {
                    if (tag !== 26) {
                        break
                    }

                    message.apSsid = reader.string()
                    continue
                }
                case 4: {
                    if (tag !== 34) {
                        break
                    }

                    message.apPassword = reader.string()
                    continue
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break
            }
            reader.skip(tag & 7)
        }
        return message
    },

    fromJSON(object: any): WifiConfig {
        return {
            staSsid: isSet(object.staSsid)
                ? globalThis.String(object.staSsid)
                : isSet(object.sta_ssid)
                  ? globalThis.String(object.sta_ssid)
                  : '',
            staPassword: isSet(object.staPassword)
                ? globalThis.String(object.staPassword)
                : isSet(object.sta_password)
                  ? globalThis.String(object.sta_password)
                  : '',
            apSsid: isSet(object.apSsid)
                ? globalThis.String(object.apSsid)
                : isSet(object.ap_ssid)
                  ? globalThis.String(object.ap_ssid)
                  : '',
            apPassword: isSet(object.apPassword)
                ? globalThis.String(object.apPassword)
                : isSet(object.ap_password)
                  ? globalThis.String(object.ap_password)
                  : '',
        }
    },

    toJSON(message: WifiConfig): unknown {
        const obj: any = {}
        if (message.staSsid !== '') {
            obj.staSsid = message.staSsid
        }
        if (message.staPassword !== '') {
            obj.staPassword = message.staPassword
        }
        if (message.apSsid !== '') {
            obj.apSsid = message.apSsid
        }
        if (message.apPassword !== '') {
            obj.apPassword = message.apPassword
        }
        return obj
    },

    create<I extends Exact<DeepPartial<WifiConfig>, I>>(base?: I): WifiConfig {
        return WifiConfig.fromPartial(base ?? ({} as any))
    },
    fromPartial<I extends Exact<DeepPartial<WifiConfig>, I>>(object: I): WifiConfig {
        const message = createBaseWifiConfig()
        message.staSsid = object.staSsid ?? ''
        message.staPassword = object.staPassword ?? ''
        message.apSsid = object.apSsid ?? ''
        message.apPassword = object.apPassword ?? ''
        return message
    },
}

function createBaseParkingStatus(): ParkingStatus {
    return { slots: [] }
}

export const ParkingStatus: MessageFns<ParkingStatus> = {
    encode(
        message: ParkingStatus,
        writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
        for (const v of message.slots) {
            SlotStatus.encode(v!, writer.uint32(10).fork()).join()
        }
        return writer
    },

    decode(input: BinaryReader | Uint8Array, length?: number): ParkingStatus {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
        const end = length === undefined ? reader.len : reader.pos + length
        const message = createBaseParkingStatus()
        while (reader.pos < end) {
            const tag = reader.uint32()
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break
                    }

                    message.slots.push(SlotStatus.decode(reader, reader.uint32()))
                    continue
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break
            }
            reader.skip(tag & 7)
        }
        return message
    },

    fromJSON(object: any): ParkingStatus {
        return {
            slots: globalThis.Array.isArray(object?.slots)
                ? object.slots.map((e: any) => SlotStatus.fromJSON(e))
                : [],
        }
    },

    toJSON(message: ParkingStatus): unknown {
        const obj: any = {}
        if (message.slots?.length) {
            obj.slots = message.slots.map((e) => SlotStatus.toJSON(e))
        }
        return obj
    },

    create<I extends Exact<DeepPartial<ParkingStatus>, I>>(base?: I): ParkingStatus {
        return ParkingStatus.fromPartial(base ?? ({} as any))
    },
    fromPartial<I extends Exact<DeepPartial<ParkingStatus>, I>>(
        object: I,
    ): ParkingStatus {
        const message = createBaseParkingStatus()
        message.slots = object.slots?.map((e) => SlotStatus.fromPartial(e)) || []
        return message
    },
}

function createBaseSlotStatus(): SlotStatus {
    return { status: 0, rfid: [], palletId: 0 }
}

export const SlotStatus: MessageFns<SlotStatus> = {
    encode(message: SlotStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
        if (message.status !== 0) {
            writer.uint32(8).int32(message.status)
        }
        for (const v of message.rfid) {
            writer.uint32(18).bytes(v!)
        }
        if (message.palletId !== 0) {
            writer.uint32(24).uint32(message.palletId)
        }
        return writer
    },

    decode(input: BinaryReader | Uint8Array, length?: number): SlotStatus {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
        const end = length === undefined ? reader.len : reader.pos + length
        const message = createBaseSlotStatus()
        while (reader.pos < end) {
            const tag = reader.uint32()
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break
                    }

                    message.status = reader.int32() as any
                    continue
                }
                case 2: {
                    if (tag !== 18) {
                        break
                    }

                    message.rfid.push(reader.bytes())
                    continue
                }
                case 3: {
                    if (tag !== 24) {
                        break
                    }

                    message.palletId = reader.uint32()
                    continue
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break
            }
            reader.skip(tag & 7)
        }
        return message
    },

    fromJSON(object: any): SlotStatus {
        return {
            status: isSet(object.status) ? slotStatus_StatusFromJSON(object.status) : 0,
            rfid: globalThis.Array.isArray(object?.rfid)
                ? object.rfid.map((e: any) => bytesFromBase64(e))
                : [],
            palletId: isSet(object.palletId)
                ? globalThis.Number(object.palletId)
                : isSet(object.pallet_id)
                  ? globalThis.Number(object.pallet_id)
                  : 0,
        }
    },

    toJSON(message: SlotStatus): unknown {
        const obj: any = {}
        if (message.status !== 0) {
            obj.status = slotStatus_StatusToJSON(message.status)
        }
        if (message.rfid?.length) {
            obj.rfid = message.rfid.map((e) => base64FromBytes(e))
        }
        if (message.palletId !== 0) {
            obj.palletId = Math.round(message.palletId)
        }
        return obj
    },

    create<I extends Exact<DeepPartial<SlotStatus>, I>>(base?: I): SlotStatus {
        return SlotStatus.fromPartial(base ?? ({} as any))
    },
    fromPartial<I extends Exact<DeepPartial<SlotStatus>, I>>(object: I): SlotStatus {
        const message = createBaseSlotStatus()
        message.status = object.status ?? 0
        message.rfid = object.rfid?.map((e) => e) || []
        message.palletId = object.palletId ?? 0
        return message
    },
}

function createBaseParkingEvent(): ParkingEvent {
    return {
        eventId: 0,
        slotId: 0,
        timestamp: 0,
        eventType: 0,
        rfid: new Uint8Array(0),
        isDone: false,
    }
}

export const ParkingEvent: MessageFns<ParkingEvent> = {
    encode(
        message: ParkingEvent,
        writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
        if (message.eventId !== 0) {
            writer.uint32(8).uint32(message.eventId)
        }
        if (message.slotId !== 0) {
            writer.uint32(16).uint32(message.slotId)
        }
        if (message.timestamp !== 0) {
            writer.uint32(24).uint64(message.timestamp)
        }
        if (message.eventType !== 0) {
            writer.uint32(32).int32(message.eventType)
        }
        if (message.rfid.length !== 0) {
            writer.uint32(42).bytes(message.rfid)
        }
        if (message.isDone !== false) {
            writer.uint32(48).bool(message.isDone)
        }
        return writer
    },

    decode(input: BinaryReader | Uint8Array, length?: number): ParkingEvent {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
        const end = length === undefined ? reader.len : reader.pos + length
        const message = createBaseParkingEvent()
        while (reader.pos < end) {
            const tag = reader.uint32()
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break
                    }

                    message.eventId = reader.uint32()
                    continue
                }
                case 2: {
                    if (tag !== 16) {
                        break
                    }

                    message.slotId = reader.uint32()
                    continue
                }
                case 3: {
                    if (tag !== 24) {
                        break
                    }

                    message.timestamp = longToNumber(reader.uint64())
                    continue
                }
                case 4: {
                    if (tag !== 32) {
                        break
                    }

                    message.eventType = reader.int32() as any
                    continue
                }
                case 5: {
                    if (tag !== 42) {
                        break
                    }

                    message.rfid = reader.bytes()
                    continue
                }
                case 6: {
                    if (tag !== 48) {
                        break
                    }

                    message.isDone = reader.bool()
                    continue
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break
            }
            reader.skip(tag & 7)
        }
        return message
    },

    fromJSON(object: any): ParkingEvent {
        return {
            eventId: isSet(object.eventId)
                ? globalThis.Number(object.eventId)
                : isSet(object.event_id)
                  ? globalThis.Number(object.event_id)
                  : 0,
            slotId: isSet(object.slotId)
                ? globalThis.Number(object.slotId)
                : isSet(object.slot_id)
                  ? globalThis.Number(object.slot_id)
                  : 0,
            timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
            eventType: isSet(object.eventType)
                ? parkingEvent_EventTypeFromJSON(object.eventType)
                : isSet(object.event_type)
                  ? parkingEvent_EventTypeFromJSON(object.event_type)
                  : 0,
            rfid: isSet(object.rfid) ? bytesFromBase64(object.rfid) : new Uint8Array(0),
            isDone: isSet(object.isDone)
                ? globalThis.Boolean(object.isDone)
                : isSet(object.is_done)
                  ? globalThis.Boolean(object.is_done)
                  : false,
        }
    },

    toJSON(message: ParkingEvent): unknown {
        const obj: any = {}
        if (message.eventId !== 0) {
            obj.eventId = Math.round(message.eventId)
        }
        if (message.slotId !== 0) {
            obj.slotId = Math.round(message.slotId)
        }
        if (message.timestamp !== 0) {
            obj.timestamp = Math.round(message.timestamp)
        }
        if (message.eventType !== 0) {
            obj.eventType = parkingEvent_EventTypeToJSON(message.eventType)
        }
        if (message.rfid.length !== 0) {
            obj.rfid = base64FromBytes(message.rfid)
        }
        if (message.isDone !== false) {
            obj.isDone = message.isDone
        }
        return obj
    },

    create<I extends Exact<DeepPartial<ParkingEvent>, I>>(base?: I): ParkingEvent {
        return ParkingEvent.fromPartial(base ?? ({} as any))
    },
    fromPartial<I extends Exact<DeepPartial<ParkingEvent>, I>>(object: I): ParkingEvent {
        const message = createBaseParkingEvent()
        message.eventId = object.eventId ?? 0
        message.slotId = object.slotId ?? 0
        message.timestamp = object.timestamp ?? 0
        message.eventType = object.eventType ?? 0
        message.rfid = object.rfid ?? new Uint8Array(0)
        message.isDone = object.isDone ?? false
        return message
    },
}

function bytesFromBase64(b64: string): Uint8Array {
    if ((globalThis as any).Buffer) {
        return Uint8Array.from(globalThis.Buffer.from(b64, 'base64'))
    } else {
        const bin = globalThis.atob(b64)
        const arr = new Uint8Array(bin.length)
        for (let i = 0; i < bin.length; ++i) {
            arr[i] = bin.charCodeAt(i)
        }
        return arr
    }
}

function base64FromBytes(arr: Uint8Array): string {
    if ((globalThis as any).Buffer) {
        return globalThis.Buffer.from(arr).toString('base64')
    } else {
        const bin: string[] = []
        arr.forEach((byte) => {
            bin.push(globalThis.String.fromCharCode(byte))
        })
        return globalThis.btoa(bin.join(''))
    }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
    ? T
    : T extends globalThis.Array<infer U>
      ? globalThis.Array<DeepPartial<U>>
      : T extends ReadonlyArray<infer U>
        ? ReadonlyArray<DeepPartial<U>>
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
    ? P
    : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
          [K in Exclude<keyof I, KeysOfUnion<P>>]: never
      }

function longToNumber(int64: { toString(): string }): number {
    const num = globalThis.Number(int64.toString())
    if (num > globalThis.Number.MAX_SAFE_INTEGER) {
        throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER')
    }
    if (num < globalThis.Number.MIN_SAFE_INTEGER) {
        throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER')
    }
    return num
}

function isSet(value: any): boolean {
    return value !== null && value !== undefined
}

export interface MessageFns<T> {
    encode(message: T, writer?: BinaryWriter): BinaryWriter
    decode(input: BinaryReader | Uint8Array, length?: number): T
    fromJSON(object: any): T
    toJSON(message: T): unknown
    create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
    fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
