/**
 * WebSocket-level mock: generates Protobuf-typed data and feeds it through
 * the real `dispatch()` pipeline (decode → mappers → Pinia stores).
 *
 * Simulation is driven by a ParkingSystem instance — each tick() executes
 * one task from the queue generated by generateParkingQueue().
 */

import {
    Parking,
    SlotStatus_Status,
    ParkingEvent_EventType,
    ScanResults_WifiAuthMode,
    DeviceStatus_WifiMode,
    type SlotStatus,
    type ParkingEvent as ProtoParkingEvent,
} from '@/services/parking'
import { dispatch, setStatus } from '@/services/websocket'
import { ParkingSystem, SlotStatus as ParkingSlotStatus } from './parkingSystem'

// ---------------------------------------------------------------------------
// HMR singleton guard (globalThis survives module re-evaluation)
// ---------------------------------------------------------------------------

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const globalState = globalThis as any

if (import.meta.hot) {
    import.meta.hot.dispose(() => {
        if (globalState.__mockInterval) {
            clearInterval(globalState.__mockInterval)
            globalState.__mockInterval = null
        }
        globalState.__isMockWsInitialized = false
    })
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function randomBytes(len: number): Uint8Array {
    const buf = new Uint8Array(len)
    for (let i = 0; i < len; i++) buf[i] = Math.floor(Math.random() * 256)
    return buf
}

function randomPlateNumber(): string {
    const a = String.fromCharCode(65 + Math.floor(Math.random() * 26))
    const b = String.fromCharCode(65 + Math.floor(Math.random() * 26))
    return `${a}${b}-${Math.floor(1000 + Math.random() * 9000)}`
}

let eventIdCounter = 1
const plateRfidNum = 6

// ---------------------------------------------------------------------------
// Encode → decode → dispatch  (full pipeline)
// ---------------------------------------------------------------------------

function sendMockMessage(msg: Parameters<typeof Parking.encode>[0]) {
    const bytes = Parking.encode(msg).finish()
    const decoded = Parking.decode(bytes)
    dispatch(decoded)
}

// ---------------------------------------------------------------------------
// Simulation state
// ---------------------------------------------------------------------------

let parkingSystem: ParkingSystem
let slots: SlotStatus[] = []
let events: ProtoParkingEvent[] = []
let activeEvent: ProtoParkingEvent | null = null

/** Maps palletId → rfid bytes for occupied pallets */
const palletRfidMap = new Map<number, Uint8Array>()

// ---------------------------------------------------------------------------
// ParkingSystem → Protobuf mapping
// ---------------------------------------------------------------------------

/**
 * Converts ParkingSystem grid state into protobuf SlotStatus[].
 */
function syncSlotsFromSystem(): SlotStatus[] {
    const result: SlotStatus[] = []

    for (let row = 0; row < parkingSystem.totalRows; row++) {
        for (let col = 0; col < parkingSystem.totalCols; col++) {
            const palletId = parkingSystem.getSlotPalletId(col, row)
            const slotId = row * parkingSystem.totalCols + col + 1
            const occupancy = parkingSystem.getSlotOccupancy(palletId)
            const taskStatus = parkingSystem.getSlotStatus(palletId)

            let status: SlotStatus_Status
            if (occupancy === 'NO_PALLET') {
                status = SlotStatus_Status.NO_PALLET
            } else if (taskStatus === ParkingSlotStatus.PENDING) {
                status = SlotStatus_Status.PENDING
            } else if (taskStatus === ParkingSlotStatus.PROCESSING) {
                status = SlotStatus_Status.PROCESSING
            } else if (occupancy === 'OCCUPIED') {
                status = SlotStatus_Status.OCCUPIED
            } else {
                status = SlotStatus_Status.EMPTY
            }

            const rfid = palletRfidMap.get(palletId)
            result.push({
                slotId,
                palletId,
                status,
                rfid: rfid ? [rfid] : [],
            })
        }
    }

    return result
}

/**
 * Finds the physical slotId (1-based) for a given palletId.
 */
function findSlotIdForPallet(palletId: number): number {
    for (let row = 0; row < parkingSystem.totalRows; row++) {
        for (let col = 0; col < parkingSystem.totalCols; col++) {
            if (parkingSystem.getSlotPalletId(col, row) === palletId) {
                return row * parkingSystem.totalCols + col + 1
            }
        }
    }
    return 0
}

// ---------------------------------------------------------------------------
// Task-queue-driven simulation
// ---------------------------------------------------------------------------

/**
 * Picks a random target pallet, generates a task queue via ParkingSystem,
 * and dispatches the initial ParkingEvent.
 */
function generateNewEvent() {
    const emptyPallets: number[] = []
    const occupiedPallets: number[] = []

    for (let row = 0; row < parkingSystem.totalRows; row++) {
        for (let col = 0; col < parkingSystem.totalCols; col++) {
            const pid = parkingSystem.getSlotPalletId(col, row)
            if (pid <= 0) continue
            const occ = parkingSystem.getSlotOccupancy(pid)
            if (occ === 'EMPTY') emptyPallets.push(pid)
            else if (occ === 'OCCUPIED') occupiedPallets.push(pid)
        }
    }

    let targetPalletId: number | null = null
    let eventType: ParkingEvent_EventType = ParkingEvent_EventType.IN
    let plateNumber = ''
    let rfid: Uint8Array = new Uint8Array()

    const random = Math.random()

    if (emptyPallets.length > 0 && random < 0.4) {
        targetPalletId = emptyPallets[Math.floor(Math.random() * emptyPallets.length)]!
        eventType = ParkingEvent_EventType.IN
        plateNumber = randomPlateNumber()
        rfid = randomBytes(plateRfidNum)
    } else if (occupiedPallets.length > 0 && random > 0.5) {
        targetPalletId =
            occupiedPallets[Math.floor(Math.random() * occupiedPallets.length)]!
        eventType = ParkingEvent_EventType.OUT
        plateNumber = ''
        rfid = palletRfidMap.get(targetPalletId) ?? randomBytes(plateRfidNum)
    }

    if (targetPalletId === null) return

    const success = parkingSystem.generateParkingQueue(targetPalletId, plateNumber)
    if (!success) return

    const slotId = findSlotIdForPallet(targetPalletId)

    activeEvent = {
        eventId: eventIdCounter++,
        slotId,
        timestamp: Date.now(),
        eventType,
        rfid,
        isDone: false,
    }

    events.push(activeEvent)
    sendMockMessage({ parkingEvent: activeEvent })

    slots = syncSlotsFromSystem()
    sendMockMessage({ parkingStatus: { slots } })
}

/**
 * Main simulation tick.
 *
 * If tasks are pending → execute one and dispatch updates.
 * Otherwise → maybe generate a new event with probability 0.8.
 */
function tick() {
    const pendingTasks = parkingSystem.getPendingTasks()

    if (pendingTasks.length > 0 && activeEvent) {
        // --- Execute next task from queue ---
        const currentTask = pendingTasks[0]!
        parkingSystem.executeNextTask()

        // Check completion
        const isCompleted = parkingSystem.getPendingTasks().length === 0
        if (isCompleted) {
            activeEvent.isDone = true
            if (currentTask.type === 'SET_SLOT_DATA') {
                if (activeEvent.eventType === ParkingEvent_EventType.IN) {
                    palletRfidMap.set(currentTask.palletId, activeEvent.rfid)
                } else {
                    palletRfidMap.delete(currentTask.palletId)
                }
            }
        }

        sendMockMessage({ parkingEvent: activeEvent })

        slots = syncSlotsFromSystem()
        sendMockMessage({ parkingStatus: { slots } })

        if (isCompleted) {
            activeEvent = null
        }
    } else if (!activeEvent) {
        // --- Maybe start a new event ---
        if (Math.random() < 0.8) {
            generateNewEvent()
        }
    }
}

// ---------------------------------------------------------------------------
// Public init
// ---------------------------------------------------------------------------

export function initMockWs() {
    if (globalState.__isMockWsInitialized) return
    globalState.__isMockWsInitialized = true

    // Simulate "connected" status
    setStatus('connected')

    // Create parking system (4 cols × 3 rows)
    parkingSystem = new ParkingSystem(4, 3)

    // Pre-populate some bottom-row pallets with plate numbers
    for (let col = 0; col < parkingSystem.totalCols; col++) {
        const pid = parkingSystem.getSlotPalletId(col, parkingSystem.totalRows - 1)
        if (pid > 0 && Math.random() < 0.5) {
            parkingSystem.setSlotData(pid, randomPlateNumber())
            palletRfidMap.set(pid, randomBytes(plateRfidNum))
        }
    }

    // Derive initial slots from ParkingSystem state
    slots = syncSlotsFromSystem()
    events = []

    // Create completed events for initially occupied pallets
    for (const slot of slots) {
        if (slot.status === SlotStatus_Status.OCCUPIED) {
            events.push({
                eventId: eventIdCounter++,
                slotId: slot.slotId,
                timestamp: Date.now() - Math.floor(Math.random() * 3600000),
                eventType: ParkingEvent_EventType.IN,
                rfid: slot.rfid[0] ?? randomBytes(plateRfidNum),
                isDone: true,
            })
        }
    }

    // Send initial parking status
    sendMockMessage({ parkingStatus: { slots } })

    // Send initial events
    for (const event of events) {
        sendMockMessage({ parkingEvent: event })
    }

    // Send mock device status
    sendMockMessage({
        wifiStatus: {
            connected: true,
            wifiMode: DeviceStatus_WifiMode.WIFI_MODE_APSTA,
            staSsid: 'ParkingNet',
            staIp: '192.168.1.42',
            apSsid: 'ESP32-Parking',
            apIp: '192.168.4.1',
            apPassword: 'parking123',
            rssi: -55,
            channel: 6,
            freeHeap: 123456,
            minFreeHeap: 98000,
            maxFreeBlockSize: 65536,
            uptimeSeconds: 3600,
        },
    })

    // Send mock scan results
    sendMockMessage({
        scanResults: {
            accessPoints: [
                {
                    ssid: 'ParkingNet',
                    bssid: new Uint8Array([0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0x01]),
                    rssi: -45,
                    channel: 6,
                    encryption: ScanResults_WifiAuthMode.WIFI_AUTH_WPA2_PSK,
                },
                {
                    ssid: 'Office-5G',
                    bssid: new Uint8Array([0x11, 0x22, 0x33, 0x44, 0x55, 0x66]),
                    rssi: -62,
                    channel: 36,
                    encryption: ScanResults_WifiAuthMode.WIFI_AUTH_WPA2_WPA3_PSK,
                },
                {
                    ssid: 'Guest',
                    bssid: new Uint8Array([0xde, 0xad, 0xbe, 0xef, 0x00, 0x01]),
                    rssi: -78,
                    channel: 1,
                    encryption: ScanResults_WifiAuthMode.WIFI_AUTH_OPEN,
                },
            ],
        },
    })

    // Start periodic simulation
    globalState.__mockInterval = setInterval(tick, 1000)
}
