/**
 * WebSocket-level mock: generates Protobuf-typed data and feeds it through
 * the real `dispatch()` pipeline (decode → mappers → Pinia stores).
 *
 * Simulation is driven by a ParkingSystem instance — each tick() executes
 * one task from the queue generated by generateParkingQueue().
 */

import {
    Parking,
    ParkingStatus_Status,
    ParkingEvent_EventType,
    ScanResults_WifiAuthMode,
    DeviceStatus_WifiMode,
    type ParkingEvent as ProtoParkingEvent,
} from '@/services/parking'
import { dispatch, setStatus } from '@/services/websocket'
import { ParkingSystem, SlotStatus as ParkingSlotStatus } from './parkingSystem'

// ---------------------------------------------------------------------------
// HMR singleton guard (globalThis survives module re-evaluation)
// ---------------------------------------------------------------------------

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const globalState = globalThis as any

if (import.meta.hot) {
    import.meta.hot.dispose(() => {
        if (globalState.__mockInterval) {
            clearInterval(globalState.__mockInterval)
            globalState.__mockInterval = null
        }
        globalState.__isMockWsInitialized = false
    })
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function randomBytes(len: number): Uint8Array {
    const buf = new Uint8Array(len)
    for (let i = 0; i < len; i++) buf[i] = Math.floor(Math.random() * 256)
    return buf
}

function randomPlateNumber(): string {
    const a = String.fromCharCode(65 + Math.floor(Math.random() * 26))
    const b = String.fromCharCode(65 + Math.floor(Math.random() * 26))
    return `${a}${b}-${Math.floor(1000 + Math.random() * 9000)}`
}

let eventIdCounter = 1

// ---------------------------------------------------------------------------
// Encode → decode → dispatch  (full pipeline)
// ---------------------------------------------------------------------------

function sendMockMessage(msg: Parameters<typeof Parking.encode>[0]) {
    const bytes = Parking.encode(msg).finish()
    const decoded = Parking.decode(bytes)
    dispatch(decoded)
}

// ---------------------------------------------------------------------------
// Simulation state
// ---------------------------------------------------------------------------

let parkingSystem: ParkingSystem
let palletGrid: number[] = []
let slots: ParkingStatus_Status[] = []
let events: ProtoParkingEvent[] = []
let activeEvent: ProtoParkingEvent | null = null

// ---------------------------------------------------------------------------
// ParkingSystem → Protobuf mapping
// ---------------------------------------------------------------------------

/**
 * Converts ParkingSystem grid state into protobuf arrays.
 *
 * - palletGrid: 12 entries (slot_id - 1 → pallet_id), preserves grid layout
 * - slots: 10 entries (pallet_id - 1 → status), only actual pallets
 *
 * NO_PALLET is NOT sent on the wire — the UI derives it from pallet_id = 0
 * in the palletGrid.
 */
function syncSlotsFromSystem(): {
    palletGrid: number[]
    slots: ParkingStatus_Status[]
} {
    const resultPallets: number[] = []

    // Find max pallet id to size the per-pallet arrays
    let maxPalletId = 0
    for (let row = 0; row < parkingSystem.totalRows; row++) {
        for (let col = 0; col < parkingSystem.totalCols; col++) {
            const pid = parkingSystem.getSlotPalletId(col, row)
            if (pid > maxPalletId) maxPalletId = pid
        }
    }

    // Build per-pallet slots array (index = pallet_id - 1)
    const resultSlots: ParkingStatus_Status[] = []
    for (let pid = 1; pid <= maxPalletId; pid++) {
        const occupancy = parkingSystem.getSlotOccupancy(pid)
        const taskStatus = parkingSystem.getSlotStatus(pid)

        let status: ParkingStatus_Status
        if (taskStatus === ParkingSlotStatus.PENDING) {
            status = ParkingStatus_Status.PENDING
        } else if (taskStatus === ParkingSlotStatus.PROCESSING) {
            status = ParkingStatus_Status.PROCESSING
        } else if (occupancy === 'OCCUPIED') {
            status = ParkingStatus_Status.OCCUPIED
        } else {
            status = ParkingStatus_Status.EMPTY
        }
        resultSlots.push(status)
    }

    // Build grid layout (12 entries: slot_id - 1 → pallet_id)
    for (let row = 0; row < parkingSystem.totalRows; row++) {
        for (let col = 0; col < parkingSystem.totalCols; col++) {
            resultPallets.push(parkingSystem.getSlotPalletId(col, row))
        }
    }

    return { palletGrid: resultPallets, slots: resultSlots }
}

/**
 * Finds the physical slotId (1-based) for a given palletId.
 */
function findSlotIdForPallet(palletId: number): number {
    for (let row = 0; row < parkingSystem.totalRows; row++) {
        for (let col = 0; col < parkingSystem.totalCols; col++) {
            if (parkingSystem.getSlotPalletId(col, row) === palletId) {
                return row * parkingSystem.totalCols + col + 1
            }
        }
    }
    return 0
}

// ---------------------------------------------------------------------------
// Task-queue-driven simulation
// ---------------------------------------------------------------------------

/**
 * Picks a random target pallet, generates a task queue via ParkingSystem,
 * and dispatches the initial ParkingEvent.
 */
function generateNewEvent() {
    const emptyPallets: number[] = []
    const occupiedPallets: number[] = []

    for (let row = 0; row < parkingSystem.totalRows; row++) {
        for (let col = 0; col < parkingSystem.totalCols; col++) {
            const pid = parkingSystem.getSlotPalletId(col, row)
            if (pid <= 0) continue
            const occ = parkingSystem.getSlotOccupancy(pid)
            if (occ === 'EMPTY') emptyPallets.push(pid)
            else if (occ === 'OCCUPIED') occupiedPallets.push(pid)
        }
    }

    let targetPalletId: number | null = null
    let eventType: ParkingEvent_EventType = ParkingEvent_EventType.IN
    let plateNumber = ''

    const random = Math.random()

    if (emptyPallets.length > 0 && random < 0.4) {
        targetPalletId = emptyPallets[Math.floor(Math.random() * emptyPallets.length)]!
        eventType = ParkingEvent_EventType.IN
        plateNumber = randomPlateNumber()
    } else if (occupiedPallets.length > 0 && random > 0.5) {
        targetPalletId =
            occupiedPallets[Math.floor(Math.random() * occupiedPallets.length)]!
        eventType = ParkingEvent_EventType.OUT
        plateNumber = ''
    }

    if (targetPalletId === null) return

    const success = parkingSystem.generateParkingQueue(targetPalletId, plateNumber)
    if (!success) return

    activeEvent = {
        eventId: eventIdCounter++,
        palletId: targetPalletId,
        // timestamp: Date.now(),
        eventType,
        isDone: false,
    }

    events.push(activeEvent)
    sendMockMessage({ parkingEvent: activeEvent })
    ;({ palletGrid, slots } = syncSlotsFromSystem())
    sendMockMessage({ parkingStatus: { palletGrid, slots } })
}

/**
 * Main simulation tick.
 *
 * If tasks are pending → execute one and dispatch updates.
 * Otherwise → maybe generate a new event with probability 0.8.
 */
function tick() {
    const pendingTasks = parkingSystem.getPendingTasks()

    if (pendingTasks.length > 0 && activeEvent) {
        // --- Execute next task from queue ---
        const currentTask = pendingTasks[0]!
        parkingSystem.executeNextTask()

        // Check completion
        const isCompleted = parkingSystem.getPendingTasks().length === 0
        if (isCompleted) {
            activeEvent.isDone = true
        }

        sendMockMessage({ parkingEvent: activeEvent })
        ;({ palletGrid, slots } = syncSlotsFromSystem())
        sendMockMessage({ parkingStatus: { palletGrid, slots } })

        if (isCompleted) {
            activeEvent = null
        }
    } else if (!activeEvent) {
        // --- Maybe start a new event ---
        if (Math.random() < 0.8) {
            generateNewEvent()
        }
    }
}

// ---------------------------------------------------------------------------
// Public init
// ---------------------------------------------------------------------------

export function initMockWs() {
    if (globalState.__isMockWsInitialized) return
    globalState.__isMockWsInitialized = true

    // Simulate "connected" status
    setStatus('connected')

    // Create parking system (4 cols × 3 rows)
    parkingSystem = new ParkingSystem(4, 3)

    // Pre-populate some bottom-row pallets with plate numbers
    for (let col = 0; col < parkingSystem.totalCols; col++) {
        const pid = parkingSystem.getSlotPalletId(col, parkingSystem.totalRows - 1)
        if (pid > 0 && Math.random() < 0.5) {
            parkingSystem.setSlotData(pid, randomPlateNumber())
        }
    }

    // Derive initial slots from ParkingSystem state
    ;({ palletGrid, slots } = syncSlotsFromSystem())
    events = []

    // Create completed events for initially occupied pallets
    for (let i = 0; i < slots.length; i++) {
        const status = slots[i]!
        const palletId = palletGrid[i] ?? 0
        if (status === ParkingStatus_Status.OCCUPIED) {
            events.push({
                eventId: eventIdCounter++,
                palletId: palletId,
                // timestamp: Date.now() - Math.floor(Math.random() * 3600000),
                eventType: ParkingEvent_EventType.IN,
                isDone: true,
            })
        }
    }

    // Send initial parking status
    sendMockMessage({ parkingStatus: { palletGrid, slots } })

    // Send initial events
    for (const event of events) {
        sendMockMessage({ parkingEvent: event })
    }

    // Send mock device status
    sendMockMessage({
        wifiStatus: {
            connected: true,
            wifiMode: DeviceStatus_WifiMode.WIFI_MODE_APSTA,
            staSsid: 'ParkingNet',
            staIp: '192.168.1.42',
            apSsid: 'ESP32-Parking',
            apIp: '192.168.4.1',
            apPassword: 'parking123',
            rssi: -55,
            channel: 6,
            freeHeap: 123456,
            minFreeHeap: 98000,
            maxFreeBlockSize: 65536,
            uptimeSeconds: 3600,
        },
    })

    // Send mock scan results
    sendMockMessage({
        scanResults: {
            accessPoints: [
                {
                    ssid: 'ParkingNet',
                    bssid: new Uint8Array([0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0x01]),
                    rssi: -45,
                    channel: 6,
                    encryption: ScanResults_WifiAuthMode.WIFI_AUTH_WPA2_PSK,
                },
                {
                    ssid: 'Office-5G',
                    bssid: new Uint8Array([0x11, 0x22, 0x33, 0x44, 0x55, 0x66]),
                    rssi: -62,
                    channel: 36,
                    encryption: ScanResults_WifiAuthMode.WIFI_AUTH_WPA2_WPA3_PSK,
                },
                {
                    ssid: 'Guest',
                    bssid: new Uint8Array([0xde, 0xad, 0xbe, 0xef, 0x00, 0x01]),
                    rssi: -78,
                    channel: 1,
                    encryption: ScanResults_WifiAuthMode.WIFI_AUTH_OPEN,
                },
            ],
        },
    })

    // Start periodic simulation
    globalState.__mockInterval = setInterval(tick, 1000)
}
